<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAp63vww\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAp63vww/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAp63vww.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAp63vww\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAp63vww\appDevDebugProjectContainer([
    'container.build_hash' => 'Ap63vww',
    'container.build_id' => '3d9b2e16',
    'container.build_time' => 1562520886,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAp63vww');
